### ISSUE TITLE
Typo: Backslash vs Forward Slash in List.cshtml

### ISSUE THREAD

**Issue by Vastlee** [OdeToCode/OdeToFood#10]
Noticed in the video & current code, when you reference the Edit page on the Add New button, your slash is a backslash, where everywhere else in the code it's a forward slash. It actually still works fine, probably through ASP.NET magic, but thought I'd mention it for consistency.

`<a asp-page=".\Edit" class="btn btn-primary">Add New</a>`

**Comment by OdeToCode** [comment]
Good catch, fixed!
