### ISSUE TITLE
Using TempData - Cookie Policy options.

### ISSUE THREAD

**Issue by heenanm** [OdeToCode/OdeToFood#11]
When following the course I was having an issue passing data into TempData. 
This caused an issue when trying to display the "Restaurant saved!" alert on the details page.

Root cause was that by default the Cookie Policy Options are set to need consent. Could be because I am in Europe.

Changed to false in Startup.cs and the issue was resolved.

**Comment by OdeToCode** [comment]
Correct - you can't have TempData without the user consenting to cookies.
