### ISSUE TITLE
Following readme: aspnet-codegenerator has no generators

### ISSUE THREAD

**Issue by swimn10s** [OdeToCode/OdeToFood#13]
In Module 3 of the Readme.md, I installed aspnet-codegenerator per instructions: dotnet tool install --global dotnet-aspnet-codegenerator.
Then tried to use razorpage generator, and command window says 

> No code generators are available in this project. Please add the 'Micrososft.VisualStudio.Web.CodeGeneration.Design' NuGet packate to the project.  Pleas add Micrososoft.VisualStudio.CodeGeneration.Design package to the project as a NuGet package reference.

Maybe there is a step missing in your instructions in Module 3 of your Readme.md to add the missing Nuget package.

**Comment by OdeToCode** [comment]
Are you running these commands in the package manager console, or in a regular cmd prompt?

**Comment by swimn10s** [comment]
From a regular command prompt.  Maybe that's the problem.   Thanks for the
quick response.

**Comment by swimn10s** [comment]
No such luck... Ran from VS package manger console, and ran into the same
problem.

**Comment by OdeToCode** [comment]
I updated the README with instructions to also add the suggested package.
