### ISSUE TITLE
error code CS0246

### ISSUE THREAD

**Issue by 209104768** [OdeToCode/OdeToFood#25]
Hi, I'm getting the following error:

- The type or namespace name 'IRestaurantData' could not be found (are you missing a using directive or an assembly reference?) 
- Startup.cs

**Comment by ngpvivek** [comment]
Verify if you have reference to the OdeToFood.Core project

**Comment by 209104768** [comment]
managed to fix my errors, it appears both the .Core and .Data library classes were created with the newer .NET Framework 3.1 and thus wasn't compatible with the version of the project, changed these and it worked.
