### ISSUE TITLE
ReadMe is missing instructions for ASP.NET Code Generator

### ISSUE THREAD

**Issue by kevingates** [OdeToCode/OdeToFood#3]
# PROBLEM:
README.md file is missing instructions.

## URL:
[Link to Course ASP.NET Fundamentals, Module 3, Clip 5: "Using the Scaffolding Tools"](https://app.pluralsight.com/player?course=aspnet-core-fundamentals&author=scott-allen&name=ba0e3835-9b2e-4444-85d5-d0732a908266&clip=4&mode=live)

## Timestamp:
0:34

## Expected:
>This is done using a tool, which is the dotnet aspnet-codegenerator. In the README file of the OdeToFood GitHub repository, I have placed some instructions on how you can install this tool. I just want to run it here to show you that you can use this tool to run a generator. There's several generators available, for areas, for controllers, for identity. The one we're using is the one for Razor Pages.

## Actual _(May 08, 2019 at 10:00 am EDT)_:
https://github.com/OdeToCode/OdeToFood#odetofood

## Suggested Fix:
Provide instructions and/or link to proper tool and 3rd-party instructions from Microsoft.

**Example:**

You will be installing the Nuget Package:
[dotnet-aspnet-codegenerator](https://www.nuget.org/packages/dotnet-aspnet-codegenerator/)

Although Microsoft's guide is in regard to Microsoft Identity, the steps for installing the code generator apply. You can follow Microsoft's instructions for installing this code via the command line from their guide on [Scaffold Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=netcore-cli).

I have reproduced the steps below: 

1. If you have not previously installed the ASP.NET Core scaffolder, install it now:
`dotnet tool install -g dotnet-aspnet-codegenerator`
2. Add a package reference to Microsoft.VisualStudio.Web.CodeGeneration.Design to the project (*.csproj) file. Run the following command in the project directory:
```
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet restore
```

**Comment by OdeToCode** [comment]
Thanks, Kevin. I added your instructions to the readme file.
