### ISSUE TITLE
Bootstrap 4 no longer has input-group-btn

### ISSUE THREAD

**Issue by Vastlee** [OdeToCode/OdeToFood#8]
In the tutorial & even after your .NET Core 3 update, the span tag in List.cshtml uses the bootstrap tag input-group-btn `<span class="input-group-btn">`

Per the [documentation](https://getbootstrap.com/docs/4.0/migration/#input-groups) from Bootstrap:
>Input groups
>
> Input group addons are now specific to their placement relative to an input. We’ve dropped .input-group-addon and `.input-group-btn` for two new classes, .input-group-prepend and .input-group-append. You must explicitly use an append or a prepend now, simplifying much of our CSS. Within an append or prepend, place your buttons as they would exist anywhere else, but wrap text in .input-group-text.
>
>Validation styles are now supported, as are multiple inputs (though you can only validate one input per group).
>
>Sizing classes must be on the parent .input-group and not the individual form elements.

**Comment by OdeToCode** [comment]
Updated, thanks.
