### ISSUE TITLE
Bootstrap 4 no longer has btn-default

### ISSUE THREAD

**Issue by Vastlee** [OdeToCode/OdeToFood#9]
In the tutorial & even after your .NET Core 3 update, the button tag in List.cshtml uses the bootstrap tag `btn-default`

Unfortunately, there doesn't seem to be an exact replacement, but per [stackoverflow](https://stackoverflow.com/questions/49202887/where-is-the-btn-default-gone-in-bootstrap-4) the closest equivalent seems to be `btn-outline-secondary`

**Comment by OdeToCode** [comment]
Thanks - I've updated to remove or replace btn-default.
